# Generated by Django 4.2.8 on 2023-12-31 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userinputmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_type', models.CharField(max_length=100)),
                ('availability', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('bhk', models.IntegerField()),
                ('society', models.CharField(max_length=100)),
                ('total_sqft', models.IntegerField()),
                ('bath', models.IntegerField()),
                ('balcony', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
