# Generated by Django 4.2.8 on 2023-12-31 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
                ('Bhk', models.IntegerField()),
                ('bathroom', models.IntegerField()),
                ('balcony', models.CharField(max_length=5)),
                ('playground', models.CharField(max_length=5)),
                ('landmark', models.CharField(max_length=50)),
                ('price_range', models.IntegerField()),
            ],
        ),
    ]
